builds:
  - id: "sway-yasm"
    main: "./cmd/sway-yasm/"
    binary: "sway-yasm"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 7

release:
  github:
    owner: pancsta
    name: sway-yasm
  draft: true
  replace_existing_draft: true
